---
name: Class-BuildMethods
version: 0.22
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Lightweight implementation-agnostic generic methods.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Class::BuildMethods:
    file: lib/Class/BuildMethods.pm
    version: 0.22
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
