--- #YAML:1.0
name: Class-BuildMethods
version: 0.12
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Lightweight implementation-agnostic generic methods."
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
